### ISSUE TITLE
update!

### ISSUE THREAD

**Issue by cheeseballs687** [mrtnRitter/DearPyGui_Animate#4]
bro update this pls its my dream😭😭😭😭😭

**Comment by sortakalpuyu** [comment]
i don't think he will update but it would be great 😔

**Comment by mrtnRitter** [comment]
Hi guys, 
sorry, I am really out of this project currently and haven't used DPG since years. 

However, I added comments in the code, which lines needs and update to latest API. Next to the [imports](https://github.com/mrtnRitter/DearPyGui_Animate/blob/main/DearPyGui_Animate/dearpygui_animate.py#L16), it's just [here](https://github.com/mrtnRitter/DearPyGui_Animate/blob/main/DearPyGui_Animate/dearpygui_animate.py#L510), [here](https://github.com/mrtnRitter/DearPyGui_Animate/blob/main/DearPyGui_Animate/dearpygui_animate.py#L542) and [here](https://github.com/mrtnRitter/DearPyGui_Animate/blob/main/DearPyGui_Animate/dearpygui_animate.py#L566).

Animating opacity was already hacky in API 0.7 and the last time I checked API, there was no hook for opacity anymore. I'm not sure if there is currently an comfortable way. One might need to referrer to the underlying C++ code of DPG.

Feel free to fork this repo and make a PR when things are working again. 

Best,
Martin

**Comment by sortakalpuyu** [comment]
Thanks for explanation and help.

**Comment by mrtnRitter** [comment]
Updated to latest version of DearPyGui thanks to the work of @IvanNazaruk
